# Special configuration file to run tests on Travis-CI via GitHub notifications
# See https://travis-ci.org/biopython/biopython/builds for results
#
# Using TravisCI's configuration alone became too complicated once we wanted
# to cover more than just running the unit tests on different versions of
# Python, so this now does all the complicated test configuration via TOX
# See file .travis-tox.ini
#
# Environment variables setup here:
# - TOXENV = environment used in Tox (conventionally uses py35 etc)
#

language: python

os:
  - linux
  - osx
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy
  - pypy3

matrix:
 include:
    - env: TOXENV=pep8
    - env: TOXENV=sdist
    - env: TOXENV=bdist_wheel

sudo: false
addons:
  apt:
    packages:
    - bwa
    - clustalo
    - clustalw
    - emboss
    - mafft
    - muscle
    - paml
    - phyml
    - probcons
    - samtools
    - wise

#There is a phyml Ubuntu package, but currently too old
before_install:
  - cd $HOME
  - mkdir bin
  - export PATH=$HOME/bin:$PATH
  - curl -L -O http://www.atgc-montpellier.fr/download/binaries/phyml/PhyML-3.1.zip
  - unzip PhyML-3.1.zip
  - mv PhyML-3.1/PhyML-3.1_linux64 bin/phyml
  - cd $TRAVIS_BUILD_DIR
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
    #  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install bwa clustal-omega clustal-w emboss mafft muscle paml phyml samtools genewise; fi
    #
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then TOXENV=py27-cover; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then TOXENV=py33-cover; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]]; then TOXENV=py34-cover; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then TOXENV=py35-cover; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "pypy" ]]; then TOXENV=pypy-nocov; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "pypy3" ]]; then TOXENV=pypy3-nocov; fi

install:
  - "cp Tests/biosql.ini.sample Tests/biosql.ini"
  - "pip install --upgrade pip setuptools"
  - "pip install tox"
  - "tox -c .travis-tox.ini -e $TOXENV --notest"

script:
  - "tox -c .travis-tox.ini -e $TOXENV"

notifications:
  email: false
